#!/usr/bin/env  bash


help()
{
	echo ""
	echo "uarmkimg - helper script to maintain usbarmory related stuff such as gnulinux rootfs/linux kernel/das u-boot loader"
	echo ""
	echo " * available actions:"
	echo ""
	echo "  setenv"
	echo "  download[=DIST[-VERSION]]"
	echo "  uboot[=VERSION]"
	echo "  linux[=VERSION]"
	echo "  rootfs=DIST[-VERSION]"
	echo "  ALL"
	
	echo ""
	echo " * samples:"
	echo ""
	echo "  setenv"
	echo "   - install required packages"
	echo ""
	echo "  uboot linux rootfs=fedora-23"
	echo "   - create dd-ready image with the latest versions of uboot and linux based on fedora 23 minimal rootfs"
	echo ""
	echo "  ALL"
	echo "   - make images using stable upstream versions of components"
	echo ""
	exit 0
}


usage()
{
	echo "usage"
	help
}


setenv()
{
	echo "setenv"
}


download()
{
	echo "download"
}


uboot()
{
	echo "uboot"
}


linux()
{
	echo "linux"
}


rootfs()
{
	echo "rootfs"
}


clean()
{
	echo "clean"
}


### static

actions="help usage setenv download uboot linux rootfs clean ALL 0"


### main


test -z "${1}" && help


for cmdarg in $@; do
	for act in $actions; do
		cmd=${cmdarg%=*}
		arg=${cmdarg#${cmd}=*}"
		if [ "${cmd}" = "${act}" ]; then
			break;
		fi;
	done;
	test "$act" = 0 && echo "ERROR: invalid command!" && help
done;

for cmdarg in $@; do
	# TODO: cmd - arg parser
	$cmdarg
done;

